EN_PAIRS = {
# ---------- Core notes ----------
"aus (unkalibriert)": "off (uncalibrated)",
"Kein gültiger PEV im Zylinder -> Abflugort = Ausflug aus dem Zylinder, +{m:.0f} Minuten Strafzeit":
    "No valid PEV inside the cylinder -> start location = exit from the cylinder, +{m:.0f} minutes penalty time",
"zu wenige Fixe mit Baro-Höhe": "too few fixes with barometric altitude",
"Aufzeichnung beginnt nicht in einer Standphase (Flugzeug bewegt sich schon)":
    "recording does not start in a stationary phase (aircraft is already moving)",
"nicht möglich: {why}": "not possible: {why}",
"Offset {o:+.0f} m auf {r:.0f} m": "offset {o:+.0f} m to {r:.0f} m",
"{d:.0f} m in {t:.0f} s": "{d:.0f} m in {t:.0f} s",
"PEV": "PEV",
"Ausflug": "Exit",
"kein Start": "no start",
"{n} PEV(s) innerhalb von {s} s nach einem PEV im Zylinder zusammengefasst (zählt als ein PEV zum ersten der Gruppe)":
    "{n} PEV(s) within {s} s after a PEV inside the cylinder merged (counts as one PEV at the time of the first of the group)",
"Kein Ausflug aus dem Zylinder nach Toröffnung gefunden -> kein gültiger Start":
    "No exit from the cylinder found after gate opening -> no valid start",
"Groundspeed am Abflug {v:.1f} km/h, {ex:.1f} km/h über Limit ({lim:.0f} km/h) -> {pts} Punkte Strafe":
    "Groundspeed at start {v:.1f} km/h, {ex:.1f} km/h over the limit ({lim:.0f} km/h) -> {pts} points penalty",
"ACHTUNG: Datum in der IGC-Datei ({a}) weicht vom eingestellten Wertungstag ({b}) ab - falsche Datei/falscher Tag?":
    "WARNING: date in the IGC file ({a}) differs from the configured contest day ({b}) - wrong file/wrong day?",
"Keine Streckenpunkte definiert - Ziel/Höhenverlust nicht geprüft":
    "No task points defined - finish/loss of height not checked",
"nicht relevanter PEV: PEV um {t} UTC ignoriert: {d:.0f} m außerhalb des Zylinders":
    "irrelevant PEV: PEV at {t} UTC ignored: {d:.0f} m outside the cylinder",
"PEV um {t} UTC {d:.0f} m außerhalb des Zylinders (innerhalb Toleranz {tol:.0f} m) -> {pts} Punkte Strafe":
    "PEV at {t} UTC {d:.0f} m outside the cylinder (within tolerance {tol:.0f} m) -> {pts} points penalty",
"Gewerteter PEV {a} UTC ist nicht der letzte PEV im Zylinder ({b} UTC): nach dem späteren PEV wäre weniger der Aufgabe geflogen -> bitte prüfen":
    "Credited PEV {a} UTC is not the last PEV inside the cylinder ({b} UTC): less of the task would have been flown after the later PEV -> please check",
"Groundspeed am Abflug {v:.1f} km/h > {lim:.0f} km/h -> kein gültiger Start":
    "Groundspeed at start {v:.1f} km/h > {lim:.0f} km/h -> no valid start",
"Baro nicht kalibriert: {why} - Höhen sind unkalibrierte Druckhöhen (Höhenverlust bleibt korrekt)":
    "Baro not calibrated: {why} - altitudes are uncalibrated pressure altitudes (loss of height remains correct)",
"Aufgabe nicht ausgewertet (kein gültiger Start)": "Task not evaluated (no valid start)",
"PEV-Intervall zwischen {a} und {b} UTC kürzer als Mindestintervall ({m} min) -> +{add:.0f} Minuten Strafzeit (vorherige Fälle prüfen: bei Wiederholung an einem weiteren Wertungstag +{sub:.0f} Minuten)":
    "PEV interval between {a} and {b} UTC shorter than the minimum interval ({m} min) -> +{add:.0f} minutes penalty time (check previous cases: on repetition on another contest day +{sub:.0f} minutes)",
"nicht gewerteter PEV: Intervall {a} -> {b} UTC < {m} min (ohne Auswirkung, nicht der gewertete PEV)":
    "non-credited PEV: interval {a} -> {b} UTC < {m} min (no effect, not the credited PEV)",
"Aufgabe nicht vollständig - fehlend: {names}": "Task not completed - missing: {names}",
"Loss of Height (baro) {loss:.0f} m, {ex:.0f} m über Limit ({lim:.0f} m) -> Strafe nach 7.4.4.7: {pts} Punkte (1 Pkt/{per:g} m, kaufmännisch gerundet)":
    "Loss of height (baro) {loss:.0f} m, {ex:.0f} m over the limit ({lim:.0f} m) -> penalty per 7.4.4.7: {pts} points (1 pt/{per:g} m, rounded half up)",
# ---------- Report ----------
"Zylinderabflug": "Cylinder start",
"Zylinderabflug-Auswertung (Annex A 7.4.4)": "Cylinder start evaluation (Annex A 7.4.4)",
"Pilot": "Pilot",
"Kennung": "Comp. ID",
"Fluggerät": "Glider",
"Datum (Datei)": "Date (file)",
"Startmethode": "Start method",
"Startzeit (UTC)": "Start time (UTC)",
"Abstand zum Zylinderrand (m, − = innen)": "Distance to cylinder edge (m, − = inside)",
"Abflughöhe Baro (m)": "Start altitude baro (m)",
"Groundspeed (km/h)": "Groundspeed (km/h)",
"Groundspeed-Basis": "Groundspeed basis",
"Ziel erreicht": "Finish reached",
"Zielzeit (UTC, interpoliert)": "Finish time (UTC, interpolated)",
"Ankunftshöhe Baro (m, interpoliert)": "Finish altitude baro (m, interpolated)",
"Höhenverlust Baro (m)": "Loss of height baro (m)",
"Strafminuten": "Penalty minutes",
"Strafpunkte Speed": "Penalty points speed",
"Strafpunkte Loss of Height": "Penalty points loss of height",
"Strafpunkte gesamt": "Penalty points total",
"Baro-Kalibrierung": "Baro calibration",
"Besonderheiten": "Remarks",
"STRAFE/UNGÜLTIG": "PENALTY/INVALID",
"PRÜFEN": "CHECK",
"Hinweis": "Note",
"Legende Zeilenfarbe:": "Row colour legend:",
"rot = Strafe / ungültig": "red = penalty / invalid",
"gelb = prüfen": "yellow = check",
"grau = nur Hinweis (z. B. Außenlandung, ignorierter PEV)": "grey = note only (e.g. outlanding, ignored PEV)",
"ja": "yes",
"nein": "no",
# ---------- GUI ----------
"SoaringSpot-Aufgabenseite": "SoaringSpot task page",
"Task notes (bitte relevante Werte manuell übernehmen)": "Task notes (please copy relevant values manually)",
"Streckenpunkt": "Task point",
"Name": "Name",
"Breite (Dezimalgrad)": "Latitude (decimal degrees)",
"Länge (Dezimalgrad)": "Longitude (decimal degrees)",
"Außenradius R1 (m)": "Outer radius R1 (m)",
"Punkt aus CUP-Datei wählen": "Choose point from CUP file",
"Zylinderabflug-Auswertetool (Annex A 7.4.4)": "Cylinder Start Evaluation Tool (Annex A 7.4.4)",
"Breite": "Latitude",
"Länge": "Longitude",
"R1 (m)": "R1 (m)",
"R2 (m)": "R2 (m)",
"A1/A2 (°)": "A1/A2 (°)",
"MaxAlt (m)": "MaxAlt (m)",
"Ziel": "Finish",
"(keine CUP-Datei gespeichert)": "(no CUP file stored)",
"{name}  ({n} Punkte, gespeichert)": "{name}  ({n} points, stored)",
"CUP-Datei gespeichert: {path} ({n} Punkte)": "CUP file stored: {path} ({n} points)",
"Aufgabe von Webseite geladen: {url}": "Task loaded from web page: {url}",
"  {n} Streckenpunkte, AAT-Zeit: {t}": "  {n} task points, AAT time: {t}",
"Aufgabe geladen aus: {path}\n  {n} Streckenpunkte, Toröffnung {gate}, Zeitzone {tz}":
    "Task loaded from: {path}\n  {n} task points, gate opening {gate}, time zone {tz}",
"Parameter gespeichert: {path}": "Parameters saved: {path}",
"Parameter geladen: {path}": "Parameters loaded: {path}",
"{n} IGC-Dateien gefunden. Starte Auswertung...": "{n} IGC files found. Starting evaluation...",
"Zylinderabflug_Report.xlsx": "Cylinder_Start_Report.xlsx",
"Start-Zylinder": "Start cylinder",
"Wertungstag": "Contest day",
"Toröffnung (Ortszeit)": "Gate opening (local time)",
"Max. Groundspeed": "Max. groundspeed",
"Max. Loss of Height": "Max. loss of height",
"PEV-Mindestintervall": "Minimum PEV interval",
"Loss-of-Height-Strafe": "Loss-of-height penalty",
"{lat:.5f}, {lon:.5f}  (Radius {r:.0f} m)": "{lat:.5f}, {lon:.5f}  (radius {r:.0f} m)",
"1 Punkt je {m:g} m über Limit (Deckelung auf Speed-/15-%-Punkte erfolgt in SeeYou)":
    "1 point per {m:g} m above the limit (capping to speed points / 15 % is done in SeeYou)",
"Fertig": "Done",
"{n} Piloten ausgewertet.\nReport: {p}": "{n} pilots evaluated.\nReport: {p}",
"(keine Notizen auf dieser Seite hinterlegt)": "(no notes stored on this page)",
"Grunddaten": "Basic data",
"Sektor/Höhe (optional - leer/0 = Vollkreis, keine Höhenbegrenzung)":
    "Sector/altitude (optional - empty/0 = full circle, no altitude limit)",
"Innenradius R2 (m):": "Inner radius R2 (m):",
"Öffnungswinkel außen A1 (°, 180=Vollkreis):": "Outer opening angle A1 (°, 180 = full circle):",
"Öffnungswinkel innen A2 (°):": "Inner opening angle A2 (°):",
"Max. Höhe MaxAlt (m, 0=unbegrenzt):": "Max. altitude MaxAlt (m, 0 = unlimited):",
"Punkt": "Point",
"Ordner": "Folders",
"Start-Zylinder (Task Sheet)": "Start cylinder (task sheet)",
"Tagesparameter (Task Sheet, national ggf. abweichend)": "Daily parameters (task sheet, may differ nationally)",
"Max. Groundspeed am Start (km/h):": "Max. groundspeed at start (km/h):",
"Max. Loss of Height (m):": "Max. loss of height (m):",
"Loss-of-Height-Strafe: Meter je Punkt:": "Loss-of-height penalty: metres per point:",
"PEV-Mindestintervall (Minuten):": "Minimum PEV interval (minutes):",
"PEV-Cluster-Fenster (Sekunden):": "PEV cluster window (seconds):",
"PEV-Toleranz außerhalb Zylinder (m, 0 = aus):": "PEV tolerance outside cylinder (m, 0 = off):",
"Strafpunkte bei Toleranz-PEV:": "Penalty points for tolerance PEV:",
"AAT-Mindestzeit (HH:MM:SS, leer=Racing Task):": "AAT minimum time (HH:MM:SS, empty = racing task):",
"Baro-Höhe kalibrieren (optional)": "Calibrate baro altitude (optional)",
"Streckenführung in Flugreihenfolge (letzter Punkt = Ziel)": "Task route in flight order (last point = finish)",
"Protokoll": "Log",
"Quellordner mit IGC-Dateien wählen": "Choose source folder with IGC files",
"Zielordner wählen": "Choose target folder",
"CUP-Datei mit den Wendepunkten wählen": "Choose CUP file with the turn points",
"Fehler": "Error",
"In der CUP-Datei wurden keine Wendepunkte gefunden.": "No turn points were found in the CUP file.",
"Nicht verfügbar": "Not available",
"Dafür fehlen die Pakete 'requests' und 'beautifulsoup4'. Bitte install.bat bzw. build_exe.bat einmal ausführen, das installiert sie automatisch.":
    "The packages 'requests' and 'beautifulsoup4' are missing. Please run install.bat or build_exe.bat once, it installs them automatically.",
"Link war keine Task-Seite - verwende automatisch: {url}": "Link was not a task page - automatically using: {url}",
"Keine Streckenpunkte gefunden": "No task points found",
"Auf dieser Seite wurden keine Streckenpunkte erkannt.": "No task points were recognised on this page.",
"Koordinaten fehlen auf dieser Seite": "Coordinates missing on this page",
"{n} Streckenpunkte gefunden (inkl. Start). Diese Seite enthält keine Koordinaten - bitte im nächsten Schritt die CUP-Datei mit den Wendepunkten wählen (wird dauerhaft gespeichert).":
    "{n} task points found (incl. start). This page contains no coordinates - in the next step please choose the CUP file with the turn points (it will be stored permanently).",
"CUP-Datei passt nicht": "CUP file does not match",
"Nicht alle Punkte gefunden": "Not all points found",
"  ACHTUNG - Koordinaten fehlen für: {names} (0.0/0.0 eingetragen)": "  WARNING - coordinates missing for: {names} (0.0/0.0 entered)",
"  Keine 'Task notes' auf dieser Seite - Toröffnung, Max. Groundspeed und Max. Loss of Height bitte manuell eintragen.":
    "  No 'task notes' on this page - please enter gate opening, max. groundspeed and max. loss of height manually.",
"Eine beliebige (originale) IGC-Datei des Wertungstages wählen": "Choose any (original) IGC file of the contest day",
"Kein SoaringSpot-Block gefunden": "No SoaringSpot block found",
"In dieser Datei wurde kein SoaringSpot-Aufgabenblock (LCU::/LSEEYOU) gefunden. Bitte eine Original-IGC-Datei von SoaringSpot verwenden, oder die Aufgabe per CUP-Datei/manuell eingeben.":
    "No SoaringSpot task block (LCU::/LSEEYOU) was found in this file. Please use an original IGC file from SoaringSpot, or enter the task via CUP file/manually.",
"Hinweis: Diese Datei enthält beim Start bereits einen Mini-Zylinder (vermutlich schon einmal verarbeitet) - bitte den echten Zylinderradius von Hand eintragen, er wurde NICHT automatisch übernommen.":
    "Note: this file already contains a mini cylinder at the start (probably processed before) - please enter the real cylinder radius by hand, it was NOT taken over automatically.",
"Bitte einen gültigen Quellordner wählen.": "Please choose a valid source folder.",
"Bitte einen Zielordner wählen.": "Please choose a target folder.",
"Keine Dateien": "No files",
"Im Quellordner wurden keine .igc-Dateien gefunden.": "No .igc files were found in the source folder.",
"auf Platzhöhe {h:.0f} m": "to field elevation {h:.0f} m",
"aus (Druckhöhe unkalibriert)": "off (pressure altitude uncalibrated)",
"Fertig. Report: {p}": "Done. Report: {p}",
"Bitte alle Zahlenfelder korrekt ausfüllen.": "Please fill in all number fields correctly.",
"CUP-Datei konnte nicht gelesen werden:\n{e}": "CUP file could not be read:\n{e}",
"CUP-Datei konnte nicht dauerhaft gespeichert werden (gilt nur für diese Sitzung):\n{e}":
    "CUP file could not be stored permanently (valid for this session only):\n{e}",
"Link nicht verwendbar": "Link not usable",
"Seite konnte nicht gelesen/erkannt werden:\n{e}": "Page could not be read/recognised:\n{e}",
"Neue CUP-Datei wählen?": "Choose a new CUP file?",
"Datei konnte nicht gelesen werden:\n{e}": "File could not be read:\n{e}",
"Bitte alle Parameter als Zahl eingeben, bevor gespeichert wird.": "Please enter all parameters as numbers before saving.",
"Bitte alle Zahlenfelder prüfen (Radius, Geschwindigkeit, ...).": "Please check all number fields (radius, speed, ...).",
"Keine Streckenpunkte": "No task points",
"Es sind keine Streckenpunkte definiert - Ziel/Höhendifferenz kann dann nicht geprüft werden. Trotzdem fortfahren?":
    "No task points are defined - finish/height difference cannot be checked. Continue anyway?",
"UNGÜLTIG": "INVALID",
"DATUM!": "DATE!",
"[{status}] {fname}: {pilot} - Start {t} UTC ({method})": "[{status}] {fname}: {pilot} - start {t} UTC ({method})",
"Link zur SoaringSpot-Seite des Tages (Task- oder Ergebnis-Seite):": "Link to the SoaringSpot page of the day (task or results page):",
"Laden": "Load",
"Abbrechen": "Cancel",
"Schließen": "Close",
"ist Ziel (letzter Punkt)": "is finish (last point)",
"Übernehmen": "Apply",
"Quellordner (IGC-Dateien):": "Source folder (IGC files):",
"Durchsuchen...": "Browse...",
"Zielordner (Kopien + Report):": "Target folder (copies + report):",
"Wendepunktdatei (CUP):": "Turn point file (CUP):",
"Wechseln...": "Change...",
"Aufgabe aus IGC-Datei laden (SoaringSpot)...": "Load task from IGC file (SoaringSpot)...",
"Aufgabe von SoaringSpot-Webseite laden...": "Load task from SoaringSpot web page...",
"Breite:": "Latitude:",
"Länge:": "Longitude:",
"Aus CUP-Datei...": "From CUP file...",
"Radius (m):": "Radius (m):",
"Toröffnung (Ortszeit HH:MM:SS):": "Gate opening (local time HH:MM:SS):",
"Zeitzone (h, ggü. UTC):": "Time zone (h, vs. UTC):",
"Wertungstag (TT.MM.JJJJ):": "Contest day (DD.MM.YYYY):",
"(Radius ggf. von Hand korrigieren, falls die geladene\nDatei bereits einen Mini-Zylinder enthält)":
    "(correct the radius by hand if the loaded\nfile already contains a mini cylinder)",
"Baro auf Referenzhöhe kalibrieren": "Calibrate baro to reference elevation",
"Platzhöhe am Start (m MSL):": "Field elevation at start (m MSL):",
"Anfangsfixe (Standphase):": "Initial fixes (stationary phase):",
"Die Anfangsfixe jeder Datei (Standphase am Boden) werden auf die Platzhöhe gesetzt. Beginnt eine Datei in der Luft, bleibt sie unkalibriert (Hinweis im Report). Der Höhenverlust ändert sich durch die Kalibrierung nicht.":
    "The initial fixes of each file (stationary phase on the ground) are set to the field elevation. If a file starts in the air it stays uncalibrated (note in the report). Loss of height is not changed by the calibration.",
"Aus CUP-Datei hinzufügen...": "Add from CUP file...",
"Manuell hinzufügen...": "Add manually...",
"Bearbeiten...": "Edit...",
"Löschen": "Delete",
"Nach oben": "Move up",
"Nach unten": "Move down",
"Parameter laden...": "Load parameters...",
"Parameter speichern...": "Save parameters...",
"Auswertung starten": "Start evaluation",
"CUP-Dateien": "CUP files",
"Alle Dateien": "All files",
"Für folgende Streckenpunkte fehlen die Koordinaten - bitte manuell nachtragen/korrigieren:":
    "Coordinates are missing for the following task points - please add/correct them manually:",
"(keine, Racing Task)": "(none, racing task)",
"IGC-Dateien": "IGC files",
"STRAFE/PRÜFEN": "PENALTY/CHECK",
"OK (Hinweis)": "OK (note)",
"  !!! {fname}: Dateidatum ({d1}) passt nicht zum Wertungstag ({d2}) !!!":
    "  !!! {fname}: file date ({d1}) does not match the contest day ({d2}) !!!",
"[FEHLER] {fname}: {e}": "[ERROR] {fname}: {e}",
"Folgende Punkte der Aufgabe wurden in der gespeicherten CUP-Datei ({name}) nicht gefunden:":
    "The following task points were not found in the stored CUP file ({name}):",
"(ohne Namen)": "(no name)",
# ---------- Web ----------
"Der Link enthält keinen konkreten Wertungstag (erwartet z. B. …/tasks/standard/task-1-on-2026-07-13 oder …/results/standard/task-1-on-2026-07-13/daily).":
    "The link does not contain a specific contest day (expected e.g. …/tasks/standard/task-1-on-2026-07-13 or …/results/standard/task-1-on-2026-07-13/daily).",
"Die Pakete 'requests' und 'beautifulsoup4' fehlen. Bitte install.bat bzw. build_exe.bat erneut ausführen (installiert sie automatisch).":
    "The packages 'requests' and 'beautifulsoup4' are missing. Please run install.bat or build_exe.bat again (it installs them automatically).",
"Konnte keine Streckenpunkt-Tabelle auf dieser Seite finden. Ist die URL wirklich eine SoaringSpot-'Task'-Seite (nicht 'results')?":
    "Could not find a task point table on this page. Is the URL really a SoaringSpot 'task' page (not 'results')?",
}
